name: Upload Test

on: [push]

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test content" > test.txt
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: test-artifact
        path: test.txt
